name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)
  workflow_dispatch: # Allows manual triggering from the Actions tab

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your project's Node.js version
          cache: 'npm' # Or 'yarn' or 'pnpm' if you use them

      - name: Install dependencies
        run: npm install # Or 'yarn install' or 'pnpm install'

      - name: Build project
        # The NEXT_PUBLIC_BASE_PATH is already set in next.config.js via env
        # NODE_ENV=production ensures isProd is true in next.config.mjs for basePath
        run: npm run build
        env:
          NODE_ENV: production

      - name: Add .nojekyll file
        # Prevents GitHub Pages from running Jekyll, which can interfere with Next.js output
        run: touch ./out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire directory for GitHub Pages to serve.
          # This should be the 'out' directory generated by `next export`.
          path: ./out

  deploy:
    needs: build # Depends on the build job completing successfully
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Output the deployed URL
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Official GitHub Action for deploying
